# Generated by Django 3.2.12 on 2022-04-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='email token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
